# Generated by Django 6.0.6 on 2026-06-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='invested_amount',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='leverage',
            field=models.IntegerField(default=100),
        ),
    ]
