# Generated by Django 6.0.6 on 2026-06-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_journalentry_invested_amount_journalentry_leverage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='pair',
            field=models.CharField(choices=[('EUR/USD', 'EUR/USD'), ('GBP/USD', 'GBP/USD'), ('USD/JPY', 'USD/JPY'), ('AUD/USD', 'AUD/USD'), ('USD/CAD', 'USD/CAD'), ('EUR/GBP', 'EUR/GBP'), ('XAU/USD', 'XAU/USD')], max_length=10),
        ),
    ]
